Iso8583 v1.3.5
ducminhgd/python-ISOMessage8583 pull request #2
Opened 2017-12-20 14:08 UTC by R2RITO

Added support for byte encoding on python3 in the getNetworkISO method since it is not automatically converted from bytes to ascii or unicode strings. 

Added function to raise an InvalidValueType exception, used to avoid repeating code.
Added verification on type for the bit setting methods, on iso creation and on usage of setBit method. Bit type verification only for types A, N, ANS.

2017-12-20 14:29 UTC, ducminhgd commented
@dat07cs, I do not maintain this repository anymore, please help me to verify if this update from @R2RITO resolves issues that he or she mentioned or not.

Thank you both!

2017-12-21 15:44 UTC, R2RITO commented
Hello @ducminhgd, have you had any answer about the merge request?

Regards.

On Dec 20, 2017 10:29, "Giã Dương Đức Minh" <notifications@github.com>
wrote:

> @dat07cs <https://github.com/dat07cs>, I do not maintain this repository
> anymore, please help me to verify if this update from @R2RITO
> <https://github.com/r2rito> resolves issues that he or she mentioned or
> not.
>
> Thank you both!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ducminhgd/python-ISOMessage8583/pull/2#issuecomment-353077392>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFP09egonxWSEG37GE9QjlrIIb4IRD0zks5tCRnQgaJpZM4RIcBa>
> .
>

2017-12-22 03:21 UTC, dat07cs commented on ISO8583/ISO8583.py
> +        if not value.isalpha():
Bit Type A can have alpha, including blank, characters

2017-12-22 03:24 UTC, dat07cs commented on ISO8583/ISO8583.py
> +        if not value.isalnum():
Bit Type ANS can have alphanumeric and special characters

2017-12-22 03:35 UTC, dat07cs commented on ISO8583/ISO8583.py
> +                    if bitType == 'A' and not value.isalpha():
As said, bit type A can have blank character

2017-12-22 03:49 UTC, dat07cs commented on ISO8583/ISO8583.py
> +            __raiseValueTypeError(bit)
forgot self

2017-12-22 03:54 UTC, dat07cs requested changes
1. miss reference to "self" object
2. bit type A can have blank character
3. bit type ANS can have special characters

2017-12-22 19:02 UTC, R2RITO reviewed
Corrected the errors, added a new function and restructured some of the code. Please review.

Thanks

2017-12-23 00:38 UTC, merged